### ISSUE TITLE
Object Corruption

### ISSUE THREAD

**Issue by DovieW** [DovieW/obsidian-android-sync#7]
![Screenshot_20231218-234554.png](https://github.com/DovieW/obsidian-android-sync/assets/32934685/d5da8cc3-0705-4dba-8148-14553e8f0bc9)

**Comment by DovieW** [comment]
![Screenshot_20231223-192131.png](https://github.com/DovieW/obsidian-android-sync/assets/32934685/a5a20dfa-9d94-4ad3-80e0-31d9dc2be8bb)

**Comment by DovieW** [comment]
When i get such issues, just going into the directory in Termux and running `git sync -ns` works

**Comment by DovieW** [comment]
Doesn't seem to actually be a network issue. if i run the Sync (all) Vaults script, it just keeps happening.

**Comment by DovieW** [comment]
the network error is from the git-sync script so that can be ignored.

I was able to fix the object file is empty with `git fsck --full`

If you need the changes from the remote, a safe bet is `git fetch && git reset --hard @{u}`

**Comment by DovieW** [comment]
maybe the fix would be to auto `git fsck --full if a sync fails. and that can be toggled with an env var and it defaults to true

**Comment by DovieW** [comment]
https://github.com/termux/termux-app/issues/3777
consider solution in last comment

**Comment by DovieW** [comment]
https://www.reddit.com/r/termux/comments/1geddlp/git_repo_in_shared_storage_object_corruption/

**Comment by DovieW** [comment]
made this script to move all my vaults to termux storage and do the worktrees thing. so far seems to be working (I think its signifcantly faster too). will check back in a couple weeks to see if it solved the issue.

the script (thanks chatgpt):
```bash
#!/bin/bash
set -euo pipefail

# Colors for echo commands
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Source and destination paths
SOURCE_PATH="/storage/emulated/0/repos/Obsidian"
DEST_PATH="$HOME/repos/Obsidian"

# Create the destination directory if it doesn't exist
echo -e "${YELLOW}Creating destination directory at $DEST_PATH if it doesn't exist...${NC}"
mkdir -p "$DEST_PATH"

# Move all repositories from source to destination
for repo in "$SOURCE_PATH"/*; do
  if [ -d "$repo/.git" ]; then

    if [ -f "$repo/.git" ]; then
      echo "$repo is a worktree. Skipping loop."
      continue
    fi
  
    # Get the name of the repository
    repo_name=$(basename "$repo")

    # Move the repository
    echo -e "${YELLOW}Moving repository $repo_name to $DEST_PATH...${NC}"
    mv "$repo" "$DEST_PATH/"

    # Change to the repository directory
    echo -e "${YELLOW}Changing to the repository directory $DEST_PATH/$repo_name...${NC}"
    cd "$DEST_PATH/$repo_name" || exit

    # Determine if the branch is 'master' or 'main'
    if git show-ref --verify --quiet refs/heads/master; then
      default_branch="master"
    elif git show-ref --verify --quiet refs/heads/main; then
      default_branch="main"
    else
      echo -e "${YELLOW}Neither 'master' nor 'main' branch found. Exiting...${NC}"
      exit 1
    fi

    git switch -c empty

    # Remove all files and directories except the .git directory
    echo -e "${YELLOW}Removing all files from the working directory of $repo_name except the .git directory...${NC}"
    find . -mindepth 1 \( -not -path "./.git" -a -not -path "./.git/*" \) -exec rm -rf {} +

    # Create a worktree for the repo back to the original location, checked out to the default branch
    echo -e "${YELLOW}Creating a worktree for $repo_name back to the original location at $SOURCE_PATH/$repo_name, checked out to $default_branch...${NC}"
    mkdir -p "$SOURCE_PATH/$repo_name"
    git worktree add "$SOURCE_PATH/$repo_name" "$default_branch"
  fi
done

echo -e "${GREEN}All repositories have been moved and worktrees created.${NC}"
```

**Comment by neonspectra** [comment]
Did you ever figure out what was happening here? I use Git on my phone from Termux and Obsidian (without any git sync plugin) as my text editor. 

I keep randomly having my local repos get corrupted this way and it's incredibly frustrating. No idea if this is an issue on the Termux side or the Obsidian side.

Doing `git fsck --full` usually fixes the corruption, but I'd really like it to not happen in the first place since eventually this is bound to give me some data loss.

**Comment by DovieW** [comment]
hey, yes i was able to solve it completely for this project.

i'm not super familiar with the exact issue but the solution is working without any issues.

essentially the problem has to do with the filesystem that is used for the main "user" files on android. git just isn't reliable there.

the solution is to keep the .git folders in the "hidden" system folders (which is reliable), and to use a Git feature called "worktrees" to have the repo seem in the user location.

you can modify the SOURCE_PATH and DEST_PATH in my script above to have it do it for you. AI is helpful with this stuff.

this seems helpful:
https://github.com/termux/termux-packages/wiki/Termux-file-system-layout

and here's some maybe helpful discussion at the bottom:
https://github.com/termux/termux-app/issues/3777

**Comment by Bakr-Ali** [comment]
Hello @DovieW ! Does following this repo's instructions prevent the above issue from happening? i.e. did you implement the fix above into the repo? Or should I just follow [this](https://medium.com/%40askar.zhakenov/obsidian-git-sync-on-android-with-termux-and-lfs-c5bb05e0f1cc) (seemingly much more complicated) setup?

Also the other setup mentions git LFS to better handle binary files. Does this repo use that?

I'm just setting things up for the first time and want to do (most) things right from the beginning to spare myself the headache of later issues as I'm not too familiar with android-git and its shenanigans.

**Comment by DovieW** [comment]
hey @Bakr-Ali 

This repo doesn't set up Git LFS as I don't keep large files in my vaults. I think it's worth skipping it if you don't plan on keeping lots of large files in your vaults as it adds complexity.

This repo/setup has a step (step 10) to run a script which uses the worktrees method to solve the corruption issue (after cloning). It's optional.

Looking at the Medium article it has a much more elegant solution to the problem. So I've opened #27 to switch to that method.

Either way you'll be fine. If you want to follow this setup, you'll have no problems. It's just slighly more complicated under the hood. Haven't had any issues since doing it a couple years ago.
